---
blank_issues_enabled: false
contact_links:
  - name: CDS Kenya Website Community Support
    url: https://github.com/apurvsibal/cdskenyawebsite/website-org/discussions
    about: Please ask and answer questions here.
